set -g @tpm_plugins '
tmux-plugins/tpm \
tmux-plugins/tmux-sensible \
tmux-plugins/tmux-resurrect \
christoomey/vim-tmux-navigator \
'
set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @rose_pine_variant 'main' 


set -gq allow-passthrough on
set -g visual-activity off

set -g status-left-length 200
set -g status-right-length 200

set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set-option -g status-position top
set -sg escape-time 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-option -g prefix C-a
unbind C-b
bind C-a send-prefix
set-window-option -g mode-keys vi
set -g mouse on

# Pane navigation
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-j select-pane -D
bind -n C-l select-pane -U

# Pane management
bind -n C-M-p split-window -h -c "#{pane_current_path}" 
bind -n C-M-v split-window -v -c "#{pane_current_path}"
bind -n C-M-S-k resize-pane -U 4
bind -n C-M-S-j resize-pane -D 4
bind -n C-M-S-h resize-pane -L 8
bind -n C-M-S-l resize-pane -R 8
bind -n C-M-x kill-pane 

# Window management
bind -n C-M-n new-window
bind -n C-M-g kill-window
bind -n C-M-j next-window
bind -n C-M-k previous-window

# Reload tmux config
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind -n C-M-s run-shell '~/.tmux/plugins/tmux-resurrect/scripts/save.sh' 
bind -n C-M-r run-shell '~/.tmux/plugins/tmux-resurrect/scripts/restore.sh' 

# Session
bind -n C-M-q kill-session
bind -n C-M-d detach
bind -n C-M-a new-session

run '~/.tmux/plugins/tpm/tpm'

set -g window-status-format ' #W '
set -g window-status-current-format '#[bold,fg=#000000,bg=#c4a8e6] #W #[default]'
set -g window-style 'default'
set -g window-active-style 'default'

set -g @rose_pine_field_separator '#[bold,fg=#eabdbb,bg=default] | #[default]'
set -g @rose_pine_left_separator ' ' 
set -g @rose_pine_right_separator ' '

set -g @rose_pine_prioritize_windows 'on' 
set -g @rose_pine_width_to_hide '80' 
set -g @rose_pine_window_count '0' 

set -g @rose_pine_only_windows 'on' 
set -g @rose_pine_window_status_separator '#[bold,fg=#eabdbb,bg=default] | #[default]' 
set -g @rose_pine_disable_active_window_menu 'on' 
set -g @rose_pine_default_window_behavior 'on' 

set -g @rose_pine_show_current_program 'off' 
set -g @rose_pine_show_pane_directory 'off' 
