font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

include rose-pine.conf

window_padding_width 5
background_opacity 0.65

cursor_shape block
cursor_blink_interval 0

# Terminal bell
enable_audio_bell no

# URL handling
url_style curly

# IME support for fcitx
update_check_interval 0
input_delay 0

confirm_os_window_close 0
