set $term kitty
bindsym $mod+Return exec $term
bindsym $mod+Shift+Return exec "kitty --class kitty-floating --name kitty-floating"

bindsym $mod+q kill
bindsym $mod+Shift+q exec --no-startup-id "xdotool getwindowfocus getwindowpid | xargs kill -9"
bindsym $mod+Control+Shift+q exec --no-startup-id "kill -9 $(ps aux --sort=-%cpu | awk 'NR==2 {print $2}')"
bindsym $mod+b exec firefox
bindsym $mod+e exec thunar "$HOME/Downloads"
bindsym $mod+r exec rofi -show drun -show-icons
bindsym $mod+p exec env CM_DIR="$HOME/.local/share" CM_LAUNCHER=rofi clipmenu
bindsym $mod+Control+p exec --no-startup-id env CM_DIR="$HOME/.local/share" $HOME/.config/i3/scripts/clipdel-rofi
bindsym $mod+Shift+p exec gnome-calculator
bindsym $mod+u exec --no-startup-id "$HOME/.config/i3/scripts/i3-save-focused-window-rule"
bindsym Print exec flameshot gui
bindsym Shift+Print exec flameshot screen --clipboard
bindsym $mod+i exec --no-startup-id sh -c 'xcolor | tr -d "\n" | xclip -selection clipboard'
