set $term kitty
bindsym $mod+Return exec $term

bindsym $mod+q kill
bindsym $mod+Shift+q exec --no-startup-id "xdotool getwindowfocus getwindowpid | xargs kill -9"
bindsym $mod+Control+Shift+q exec --no-startup-id "kill -9 $(ps aux --sort=-%cpu | awk 'NR==2 {print $2}')"
bindsym $mod+b exec firefox
bindsym $mod+e exec thunar
bindsym $mod+r exec rofi -show drun -show-icons
bindsym $mod+p exec CM_LAUNCHER=rofi clipmenu
bindsym $mod+Shift+p exec gnome-calculator
bindsym Print exec flameshot gui
bindsym Shift+Print exec flameshot screen --clipboard
