exec feh --bg-fill ~/.config/i3/wallpaper.png
exec --no-startup-id quickshell -p ~/.config/quickshell
exec --no-startup-id env CM_DIR="$HOME/.local/share" clipmenud
exec --no-startup-id dunst
exec --no-startup-id picom
exec --no-startup-id redshift
exec --no-startup-id dex -a -s /etc/xdg/autostart/:~/.config/autostart/
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec --no-startup-id obs --startreplaybuffer --minimize-to-tray
