bindsym XF86AudioRaiseVolume exec "pamixer -ui 2 && $HOME/.config/eww/scripts/show-volume-osd.sh"
bindsym XF86AudioLowerVolume exec "pamixer -ud 2 && $HOME/.config/eww/scripts/show-volume-osd.sh"
bindsym XF86AudioMute exec "pamixer -t && $HOME/.config/eww/scripts/show-volume-osd.sh"
bindsym $mod+m exec --no-startup-id "$HOME/.config/i3/scripts/i3-cycle-focused-audio-sink"
