bindsym XF86AudioRaiseVolume exec "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+ && $HOME/.config/i3/scripts/show-volume-osd.sh"
bindsym XF86AudioLowerVolume exec "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%- && $HOME/.config/i3/scripts/show-volume-osd.sh"
bindsym XF86AudioMute exec "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && $HOME/.config/i3/scripts/show-volume-osd.sh"
bindsym $mod+XF86AudioRaiseVolume exec --no-startup-id "$HOME/.config/i3/scripts/i3-focused-app-volume +2%"
bindsym $mod+XF86AudioLowerVolume exec --no-startup-id "$HOME/.config/i3/scripts/i3-focused-app-volume -2%"
bindsym $mod+m exec --no-startup-id "$HOME/.config/quickshell/scripts/toggle-volume-modal.sh"
bindsym $mod+shift+m exec --no-startup-id "$HOME/.config/i3/scripts/i3-cycle-focused-audio-sink"
