set $noop exec --no-startup-id true

mode "locked" {
        bindsym $mod+Return $noop
        bindsym $mod+Shift+Return $noop
        bindsym $mod+q $noop
        bindsym $mod+Shift+q $noop
        bindsym $mod+Control+Shift+q $noop
        bindsym $mod+b $noop
        bindsym $mod+e $noop
        bindsym $mod+r $noop
        bindsym $mod+p $noop
        bindsym $mod+Control+p $noop
        bindsym $mod+Control+Shift+p $noop
        bindsym $mod+Shift+p $noop
        bindsym $mod+u $noop
        bindsym Print $noop
        bindsym Shift+Print $noop
        bindsym $mod+i $noop
        bindsym $mod+h $noop
        bindsym $mod+j $noop
        bindsym $mod+k $noop
        bindsym $mod+l $noop
        bindsym $mod+Left $noop
        bindsym $mod+Down $noop
        bindsym $mod+Up $noop
        bindsym $mod+Right $noop
        bindsym $mod+Shift+Left $noop
        bindsym $mod+Shift+Down $noop
        bindsym $mod+Shift+Up $noop
        bindsym $mod+Shift+Right $noop
        bindsym $mod+Shift+j $noop
        bindsym $mod+w $noop
        bindsym $mod+t $noop
        bindsym $mod+a $noop
        bindsym $mod+s $noop
        bindsym $mod+d $noop
        bindsym $mod+f $noop
        bindsym $mod+z $noop
        bindsym $mod+x $noop
        bindsym $mod+c $noop
        bindsym $mod+v $noop
        bindsym $mod+Shift+a $noop
        bindsym $mod+Shift+s $noop
        bindsym $mod+Shift+d $noop
        bindsym $mod+Shift+f $noop
        bindsym $mod+Shift+z $noop
        bindsym $mod+Shift+x $noop
        bindsym $mod+Shift+c $noop
        bindsym $mod+Shift+v $noop
        bindsym $mod+Shift+r $noop
        bindsym $mod+o $noop
        bindsym $mod+Shift+e $noop
        bindsym XF86AudioRaiseVolume $noop
        bindsym XF86AudioLowerVolume $noop
        bindsym XF86AudioMute $noop
        bindsym $mod+XF86AudioRaiseVolume $noop
        bindsym $mod+XF86AudioLowerVolume $noop
        bindsym $mod+m $noop
        bindsym $mod+Shift+m $noop
        bindsym Mod1+Tab $noop
        bindsym Mod1+Shift+Tab $noop
        bindsym Alt+F4 $noop
        bindsym Control+Alt+BackSpace $noop
        bindsym XF86PowerOff $noop
        bindsym XF86Sleep $noop
        bindsym XF86ScreenSaver $noop
        bindsym XF86MonBrightnessUp $noop
        bindsym XF86MonBrightnessDown $noop
        bindsym Pause $noop
}

mode "resize" {
        bindsym Left resize shrink width 5 px or 5 ppt
        bindsym Down resize grow height 5 px or 5 ppt
        bindsym Up resize shrink height 5 px or 5 ppt
        bindsym Right resize grow width 5 px or 5 ppt

        bindsym Return mode "default"
        bindsym Escape mode "default"
}
