for_window [title="Calculator"] floating enable
for_window [title="Timer"] floating enable
for_window [class="^.*"] border pixel 1
for_window [class="librewolf"] border none
for_window [class="firefox"] border none
for_window [class="mpv"] floating enable
for_window [class="imv"] floating enable
for_window [class="zenity"] floating enable
for_window [class="cachyos-welcome"] floating enable
for_window [class="^kitty-floating$" instance="^kitty-floating$"] floating enable, resize set 1200 px 800 px, move position center
# opencode-window-state class=Thunar instance=thunar
for_window [class="^Thunar$" instance="^thunar$"] fullscreen disable, floating enable, resize set 1193 px 794 px, move position center
# opencode-window-state class=kitty instance=kitty
for_window [class="^kitty$" instance="^kitty$"] fullscreen disable, floating disable
# opencode-window-state class=vlc instance=vlc
for_window [class="^vlc$" instance="^vlc$"] fullscreen disable, floating enable, resize set 1434 px 899 px, move position center
