set $ws1 "1:A"
set $ws2 "2:S"
set $ws3 "3:D"
set $ws4 "4:F"
set $ws5 "5:Z"
set $ws6 "6:X"
set $ws7 "7:C"
set $ws8 "8:V"

workspace $ws1 output HDMI-1
workspace $ws2 output HDMI-1
workspace $ws3 output HDMI-1
workspace $ws4 output HDMI-1
workspace $ws5 output eDP-1
workspace $ws6 output eDP-1
workspace $ws7 output eDP-1
workspace $ws8 output eDP-1
