set $ws1 "1:A"
set $ws2 "2:S"
set $ws3 "3:D"
set $ws4 "4:F"
set $ws5 "5:Z"
set $ws6 "6:X"
set $ws7 "7:C"
set $ws8 "8:V"

workspace $ws1 output $primary_output
workspace $ws2 output $primary_output
workspace $ws3 output $primary_output
workspace $ws4 output $primary_output
workspace $ws5 output $secondary_output
workspace $ws6 output $secondary_output
workspace $ws7 output $secondary_output
workspace $ws8 output $secondary_output
